spring.application.name=CareBot_integration3_team17
server.port=8080
logging.level.root=DEBUG

spring.datasource.url=jdbc:mysql://10.134.178.167/game
spring.datasource.username=postgres
spring.datasource.password=DBP@ss
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Delivery
