
    /*DELIVERY_ID INT,
    OBSTACLE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DISTANCE DECIMAL(5,2),
    OBSTACLES INT,
    DROP_POINT VARCHAR(50),
    STATUS VARCHAR(50)*/

DROP TABLE IF EXISTS OBSTACLE_TABLE;
DROP TABLE IF EXISTS DELIVERY_TABLE;

    CREATE TABLE DELIVERY_TABLE (
                                    DELIVERY_ID INTEGER CONSTRAINT DELIVERY_PK PRIMARY KEY,
                                    DELIVERY_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    OBSTACLE_QUANTITY INTEGER,
                                    DROP_POINT VARCHAR(50),
                                    STATUS VARCHAR(50)
    );

  CREATE TABLE IF NOT EXISTS OBSTACLE_TABLE (
    DELIVERY_ID INTEGER CONSTRAINT DELIVERY_FK REFERENCES DELIVERY_TABLE,
    OBSTACLE_ID INTEGER,
    OBSTACLE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

