
    /*DELIVERY_ID INT,
    OBSTACLE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DISTANCE DECIMAL(5,2),
    OBSTACLES INT,
    DROP_POINT VARCHAR(50),
    STATUS VARCHAR(50)*/

DROP TABLE IF EXISTS OBSTACLE_TABLE;
DROP TABLE IF EXISTS DELIVERY_TABLE;


    CREATE TABLE DELIVERY_TABLE (
                                    DELIVERY_ID INTEGER CONSTRAINT DELIVERY_PK PRIMARY KEY,
                                    DELIVERY_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    OBSTACLE_QUANTITY INTEGER DEFAULT 1,
                                    DROP_POINT VARCHAR(50),
                                    STATUS VARCHAR(50)
    );

  CREATE TABLE IF NOT EXISTS OBSTACLE_TABLE (
    DELIVERY_ID INTEGER CONSTRAINT DELIVERY_FK REFERENCES DELIVERY_TABLE,
    OBSTACLE_ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    OBSTACLE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OBSTACLE_DISTANCE INTEGER
  );

INSERT INTO DELIVERY_TABLE(DELIVERY_ID, DROP_POINT, STATUS) VALUES (1, 3, 'STOPPED');

INSERT INTO OBSTACLE_TABLE(delivery_id, OBSTACLE_TIMESTAMP, obstacle_distance) VALUES (1, CURRENT_TIMESTAMP, 20);
    SET TIMEZONE = 'Europe/Berlin';
SELECT DELIVERY_ID, OBSTACLE_TIMESTAMP, OBSTACLE_DISTANCE
FROM OBSTACLE_TABLE
ORDER BY 2 DESC;